update workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -85,16 +85,16 @@ jobs:
             exit 1
           fi
 
-      COVERAGE=$(genhtml --quiet --output-directory out --branch-coverage --function-coverage coverage/lcov.info | grep -Po '(?<=lines......: )\d+')
-      if [ -z "$COVERAGE" ]; then
-        echo "Failed to extract coverage percentage."
-        exit 1
-      fi
+          COVERAGE=$(genhtml --quiet --output-directory out --branch-coverage --function-coverage coverage/lcov.info | grep -Po '(?<=lines......: )\d+')
+          if [ -z "$COVERAGE" ]; then
+            echo "Failed to extract coverage percentage."
+            exit 1
+          fi
 
-      echo "Coverage is ${COVERAGE}%"
-      
-      # Generate the badge
-      curl "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen" -o coverage-badge.svg
+          echo "Coverage is ${COVERAGE}%"
+          
+          # Generate the badge
+          curl "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen" -o coverage-badge.svg
 
 
       - name: Commit and Push Badge Update
