update workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -66,16 +66,36 @@ jobs:
       #   with:
       #     path: ./coverage/lcov.info
       #     min_coverage: 0
-      
+
       - name: Install lcov
         run: sudo apt-get install -y lcov  # Install lcov and genhtml
 
       - name: Parse Coverage and Generate Badge
         run: |
-          COVERAGE=$(genhtml --quiet --output-directory out --branch-coverage --function-coverage coverage/lcov.info | grep -Po '(?<=lines......: )\d+')
-          echo "Coverage is ${COVERAGE}%"
+          # Check if lcov.info exists
+          if [ ! -f coverage/lcov.info ]; then
+            echo "coverage/lcov.info file not found!"
+            exit 1
+          fi
 
-          curl "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen" -o coverage-badge.svg
+          # Parse the coverage
+          genhtml --quiet --output-directory out --branch-coverage --function-coverage coverage/lcov.info
+          if [ $? -ne 0 ]; then
+            echo "genhtml command failed."
+            exit 1
+          fi
+
+      COVERAGE=$(genhtml --quiet --output-directory out --branch-coverage --function-coverage coverage/lcov.info | grep -Po '(?<=lines......: )\d+')
+      if [ -z "$COVERAGE" ]; then
+        echo "Failed to extract coverage percentage."
+        exit 1
+      fi
+
+      echo "Coverage is ${COVERAGE}%"
+      
+      # Generate the badge
+      curl "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen" -o coverage-badge.svg
+
 
       - name: Commit and Push Badge Update
         run: |
